services:
  - type: web
    name: log-tracker
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn worklog.wsgi:application
    envVars:
      - key: DATABASE_URL
        sync: false
    autoDeploy: true
    buildFilter:
      paths:
        - "**/*.py"
        - requirements.txt
        - render.yaml
    preDeployCommand: |
      python manage.py collectstatic --noinput
      python manage.py migrate
      echo "from django.contrib.auth import get_user_model; \
      User = get_user_model(); \
      User.objects.filter(username='admin').exists() or \
      User.objects.create_superuser('admin', 'admin@example.com', 'admin1234')" | python manage.py shell
