# Generated by Django 5.2.3 on 2025-06-24 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workreport',
            name='report_file',
            field=models.FileField(blank=True, null=True, upload_to='report_files/'),
        ),
    ]
