# Generated by Django 5.2.3 on 2025-06-24 02:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_pendingregistration_alter_workreport_report_file_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pendingregistration',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pendingregistration',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='pendingregistration',
            name='password',
        ),
        migrations.RemoveField(
            model_name='pendingregistration',
            name='username',
        ),
        migrations.AddField(
            model_name='pendingregistration',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
